//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mulakat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odio_detay
    {
        public int ID { get; set; }
        public string KANAAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<double> sagIKIYUZELLI { get; set; }
        public Nullable<double> sagBESYUZ { get; set; }
        public Nullable<double> sagBIR { get; set; }
        public Nullable<double> sagIKI { get; set; }
        public Nullable<double> sagUC { get; set; }
        public Nullable<double> sagDORT { get; set; }
        public Nullable<double> sagALTI { get; set; }
        public Nullable<double> sagSEKIZ { get; set; }
        public Nullable<double> solIKIYUZELLI { get; set; }
        public Nullable<double> solBESYUZ { get; set; }
        public Nullable<double> solBIR { get; set; }
        public Nullable<double> solIKI { get; set; }
        public Nullable<double> solUC { get; set; }
        public Nullable<double> solDORT { get; set; }
        public Nullable<double> SolALTI { get; set; }
        public Nullable<double> SolSEKİZ { get; set; }
    }
}
